FROM certbot/certbot

ENV DOMAINS=""
ENV EMAIL=""

VOLUME /etc/letsencrypt
VOLUME /var/www/certbot

ENTRYPOINT for domain in ${DOMAINS}; do echo "Processing $domain..."; certbot -t certonly --webroot --agree-tos --non-interactive -w /var/www/certbot -m ${EMAIL} -d ${domain} -d *.${domain} -vv; done; certbot renew -q