FROM certbot/dns-google

ENV DOMAINS=""
ENV EMAIL=""
ENV GOOGLE_CREDS=""

VOLUME /etc/letsencrypt
VOLUME /var/www/certbot

ENTRYPOINT for domain in ${DOMAINS}; do echo "Processing $domain..."; certbot -t certonly --dns-google --dns-google-credentials ${GOOGLE_CREDS} --agree-tos --non-interactive -w /var/www/certbot -m ${EMAIL} -d $domain -d *.$domain -vv; done; \
    while true; do certbot renew -q; sleep 10h; done