FROM certbot/dns-route53

#DOMAIN=example.com
#EMAIL=user@example.com
#ANDWILDCARD="-d dl.example.com -d as.example.com -d ab.example.com"

ENV DOMAIN=""   
ENV EMAIL=""    
ENV ANDWILDCARD="" 

VOLUME /etc/letsencrypt
VOLUME /var/www/certbot

ENTRYPOINT if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then echo "processing cert for domain ${DOMAIN} and if any additional domain ${ANDWILDCARD} ..." ; certbot -t certonly --dns-route53 --agree-tos --non-interactive -w /var/www/certbot -m ${EMAIL} -d ${DOMAIN} ${ANDWILDCARD} -vv; else echo "Certs for ${DOMAIN} is already exists, hence skipping generation. Renewing the cert...."; certbot renew; fi
