FROM busybox:1.35.0-uclibc as busybox
FROM certbot/dns-route53

ENV DOMAIN=""
ENV EMAIL=""

VOLUME /etc/letsencrypt
VOLUME /var/www/certbot
COPY --from=busybox /bin/sh /bin/sh


ENTRYPOINT if [ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then echo "processing..." ; certbot -t certonly --dns-route53 --agree-tos --non-interactive -w /var/www/certbot -m ${EMAIL} -d $DOMAIN -v; else echo "Certs exists"; fi