# version: 2.1
# jobs:
#   build:
#     environment:
#       CERTBOT_IMAGE: datagenx/certbot
#       CERTBOT_DOCKERFILE: dockerfile-certbot
#       AWS_CERTBOT_IMAGE: datagenx/certbot-dns-route53
#       AWS_CERTBOT_DOCKERFILE: dockerfile-certbot-aws
#       GCP_CERTBOT_IMAGE: datagenx/certbot-dns-google
#       GCP_CERTBOT_DOCKERFILE: dockerfile-certbot-gcp
#     docker:
#       - image: cimg/base:stable
#     resource_class: small
#     steps:
#       - checkout
#       - setup_remote_docker:
#           version: 20.10.18
#           docker_layer_caching: true
#       - run:
#           name: Build Docker certbot image
#           command: docker build -t $CERTBOT_IMAGE:latest -f $CERTBOT_DOCKERFILE .
#       - run:
#           name: Build Docker dns-route53 certbot image
#           command: docker build -t $AWS_CERTBOT_IMAGE:latest -f $AWS_CERTBOT_DOCKERFILE .
#       - run:
#           name: Build Docker google-dns certbot image
#           command: docker build -t $GCP_CERTBOT_IMAGE:latest -f $GCP_CERTBOT_DOCKERFILE .

#       - run:
#           name: Publish certbot Docker Image to Docker Hub
#           command: |
#             IMAGE_TAG="0.1.$CIRCLE_BUILD_NUM"
#             echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#             docker tag $CERTBOT_IMAGE:latest $CERTBOT_IMAGE:$IMAGE_TAG
#             docker push $CERTBOT_IMAGE:latest
#             docker push $CERTBOT_IMAGE:$IMAGE_TAG
#       - run:
#           name: Publish dns-route53 certbot Docker Image to Docker Hub
#           command: |
#             IMAGE_TAG="0.1.$CIRCLE_BUILD_NUM"
#             echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#             docker tag $AWS_CERTBOT_IMAGE:latest $AWS_CERTBOT_IMAGE:$IMAGE_TAG
#             docker push $AWS_CERTBOT_IMAGE:latest
#             docker push $AWS_CERTBOT_IMAGE:$IMAGE_TAG
#       - run:
#           name: Publish google-dns certbot Docker Image to Docker Hub
#           command: |
#             IMAGE_TAG="0.1.$CIRCLE_BUILD_NUM"
#             echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#             docker tag $GCP_CERTBOT_IMAGE:latest $GCP_CERTBOT_IMAGE:$IMAGE_TAG
#             docker push $GCP_CERTBOT_IMAGE:latest
#             docker push $GCP_CERTBOT_IMAGE:$IMAGE_TAG

# workflows:
#   version: 2
#   build-main:
#     jobs:
#       - build:
#           context:
#             - cci-ctx
#           filters:
#             branches:
#               only: main
# # daily-run-workflow:
# #   triggers:
# #     - schedule:
# #         # “At 00:05 on every 2nd day-of-month.”
# #         cron: "5 0 */2 * *"
# #         filters:
# #           branches:
# #             only:
# #               - main
# #       jobs:
# #         - build:
# #             context:
# #               - cci-ctx
